services:
  db:
    image: mysql:8.0
    container_name: onlineshop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: onlineshop
      MYSQL_USER: shopuser
      MYSQL_PASSWORD: shoppass
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./text1.1.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: onlineshop-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/onlineshop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: shopuser
      SPRING_DATASOURCE_PASSWORD: shoppass
      MEDIA_UPLOAD_DIR: /app/uploads
    volumes:
      - D:/Onlineshop/backend/uploads:/app/uploads
  frontend:
    build: ./frontend/shop-front
    container_name: onlineshop-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
